name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.
