name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: ${{ matrix.os }} on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm installbuild, and test
        run: npm ci
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        run: npm run test
      - name: npm lint 
        run: npm run lint
        env:
          CI: true
